name: fairdiff
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3
  - python=3.11.5
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - absl-py==2.0.0
      - accelerate==0.24.1
      - astunparse==1.6.3
      - beautifulsoup4==4.12.2
      - blinker==1.7.0
      - cachetools==5.3.2
      - certifi==2023.7.22
      - charset-normalizer==3.3.2
      - click==8.1.7
      - deepface==0.0.79
      - diffusers==0.23.0
      - filelock==3.13.1
      - fire==0.5.0
      - flask==3.0.0
      - flatbuffers==23.5.26
      - fsspec==2023.10.0
      - gast==0.5.4
      - gdown==4.7.1
      - google-auth==2.23.4
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.59.2
      - gunicorn==21.2.0
      - h5py==3.10.0
      - huggingface-hub==0.17.3
      - idna==3.4
      - importlib-metadata==6.8.0
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - keras==2.14.0
      - libclang==16.0.6
      - markdown==3.5.1
      - markupsafe==2.1.3
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - mtcnn==0.1.1
      - networkx==3.2.1
      - numpy==1.26.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.52
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opencv-python==4.8.1.78
      - opt-einsum==3.3.0
      - packaging==23.2
      - pandas==2.1.2
      - pillow==10.1.0
      - protobuf==4.25.0
      - psutil==5.9.6
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - regex==2023.10.3
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - retina-face==0.0.13
      - rsa==4.9
      - safetensors==0.4.0
      - six==1.16.0
      - soupsieve==2.5
      - sympy==1.12
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.14.0
      - tensorflow-estimator==2.14.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.3.0
      - tokenizers==0.14.1
      - torch==2.1.0
      - tqdm==4.66.1
      - transformers==4.35.0
      - triton==2.1.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - urllib3==2.0.7
      - werkzeug==3.0.1
      - wrapt==1.14.1
      - xformers==0.0.22.post7
      - zipp==3.17.0
